# Generated by Django 5.1.15 on 2026-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Your Instagram username, e.g. katyperry.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin_url_segment',
            field=models.CharField(blank=True, help_text="Your Linkedin url segment after 'linkedin.com/', e.g. in/katyperry or company/katy-perry-collections.", max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='tiktok_handle',
            field=models.CharField(blank=True, help_text='Your TikTok username, e.g. katyperry.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your Twitter username without the @, e.g. katyperry.', max_length=255),
        ),
    ]
