# Generated by Django 6.0.6 on 2026-06-12 06:58

import core.tokens
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_theme', models.CharField(choices=[('minimal_saas', 'Minimal SaaS'), ('agency', 'Agency'), ('corporate', 'Corporate'), ('editorial', 'Editorial'), ('bold_startup', 'Bold Startup')], default='minimal_saas', max_length=32)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('accent_color', models.CharField(default='#ecfe3a', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#111827', max_length=7)),
                ('color_schemes', models.JSONField(default=core.tokens.default_color_schemes)),
                ('heading_font', models.CharField(choices=[('Inter, ui-sans-serif, system-ui, sans-serif', 'Inter / system'), ('ui-sans-serif, system-ui, sans-serif', 'System sans'), ('ui-serif, Georgia, Cambria, serif', 'System serif'), ('ui-monospace, SFMono-Regular, Menlo, monospace', 'System mono')], default='Inter, ui-sans-serif, system-ui, sans-serif', max_length=128)),
                ('body_font', models.CharField(choices=[('Inter, ui-sans-serif, system-ui, sans-serif', 'Inter / system'), ('ui-sans-serif, system-ui, sans-serif', 'System sans'), ('ui-serif, Georgia, Cambria, serif', 'System serif'), ('ui-monospace, SFMono-Regular, Menlo, monospace', 'System mono')], default='Inter, ui-sans-serif, system-ui, sans-serif', max_length=128)),
                ('button_font', models.CharField(choices=[('Inter, ui-sans-serif, system-ui, sans-serif', 'Inter / system'), ('ui-sans-serif, system-ui, sans-serif', 'System sans'), ('ui-serif, Georgia, Cambria, serif', 'System serif'), ('ui-monospace, SFMono-Regular, Menlo, monospace', 'System mono')], default='Inter, ui-sans-serif, system-ui, sans-serif', max_length=128)),
                ('button_shape', models.CharField(choices=[('square', 'Square'), ('soft', 'Soft'), ('rounded', 'Rounded'), ('pill', 'Pill')], default='soft', max_length=16)),
                ('button_border_width', models.PositiveSmallIntegerField(default=1)),
                ('button_padding', models.CharField(default='normal', max_length=16)),
                ('image_radius', models.CharField(choices=[('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=16)),
                ('image_shadow', models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('medium', 'Medium'), ('strong', 'Strong')], default='soft', max_length=16)),
                ('placeholder_style', models.CharField(choices=[('minimal', 'Minimal'), ('brand_mark', 'Brand mark'), ('pattern', 'Pattern'), ('gradient', 'Gradient')], default='brand_mark', max_length=32)),
                ('cookie_banner_enabled', models.BooleanField(default=False)),
                ('cookie_banner_text', models.CharField(blank=True, default='We use cookies to improve your experience.', max_length=255)),
                ('analytics_id', models.CharField(blank=True, max_length=80)),
                ('custom_css_variables', models.TextField(blank=True, help_text='Superuser-only escape hatch. Add CSS variable declarations only.')),
                ('head_html', models.TextField(blank=True)),
                ('footer_html', models.TextField(blank=True)),
                ('default_avatar_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('default_card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('default_hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site design settings',
            },
        ),
    ]
