# Generated by Django 6.0.6 on 2026-06-13 07:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_anchor_id',
            field=models.CharField(blank=True, default='clients', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_cta_text',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_layout',
            field=models.CharField(choices=[('centered_heading_row', 'Centered heading with logo row'), ('row_cta', 'Logo row with CTA'), ('left_heading_row', 'Left heading with logo row'), ('split_copy_grid', 'Split copy with logo grid'), ('bordered_grid', 'Bordered logo grid')], default='centered_heading_row', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_primary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_secondary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_anchor_id',
            field=models.CharField(blank=True, default='cta', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_image_alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_layout',
            field=models.CharField(choices=[('left_stack', 'Left stacked'), ('centered', 'Centered'), ('horizontal_split', 'Horizontal split'), ('media_left', 'Media left')], default='left_stack', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_anchor_id',
            field=models.CharField(blank=True, default='features', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_image_alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_layout',
            field=models.CharField(choices=[('list_media_right', 'Feature list with media right'), ('centered_two_column', 'Centered two-column grid'), ('media_grid', 'Media with feature grid'), ('heading_media_below', 'Heading with media below'), ('centered_three_column', 'Centered three-column grid'), ('media_left_list', 'Media left with feature list'), ('card_columns', 'Three-column feature cards'), ('split_media_list', 'Split media with feature list'), ('split_media_testimonial', 'Split media with testimonial'), ('heading_left_grid', 'Heading left with feature grid'), ('intro_checklist', 'Intro with checklist grid'), ('feature_grid', 'Feature grid')], default='list_media_right', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='large', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_testimonial_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_testimonial_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_testimonial_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_testimonial_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_anchor_id',
            field=models.CharField(blank=True, default='hero', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_announcement',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_announcement_link_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_announcement_link_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_layout',
            field=models.CharField(choices=[('centered_simple', 'Centered simple'), ('split_media_right', 'Split media right'), ('background_media', 'Background media'), ('centered_media_below', 'Centered with media below'), ('half_media_right', 'Half media right'), ('angled_media_right', 'Angled media right')], default='centered_simple', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='large', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='DesignSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_font', models.CharField(default='Poppins', max_length=120)),
                ('body_font', models.CharField(default='Nunito', max_length=120)),
                ('base_font_size', models.PositiveSmallIntegerField(default=16)),
                ('brand_color', models.CharField(default='#4f46e5', max_length=16)),
                ('background_color', models.CharField(default='#ffffff', max_length=16)),
                ('surface_color', models.CharField(default='#f8f9fa', max_length=16)),
                ('text_color', models.CharField(default='#111827', max_length=16)),
                ('muted_text_color', models.CharField(default='#667085', max_length=16)),
                ('section_padding', models.PositiveSmallIntegerField(default=80, help_text='Default vertical section padding in pixels.')),
                ('container_width', models.PositiveSmallIntegerField(default=1200, help_text='Maximum content width in pixels.')),
                ('button_radius', models.PositiveSmallIntegerField(default=6)),
                ('card_radius', models.PositiveSmallIntegerField(default=12)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_logos', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(blank=True, help_text='Short icon name or initials.', max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
