# Generated by Django 6.0.6 on 2026-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_clients_anchor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designsystemsettings',
            old_name='muted_text_color',
            new_name='text_muted_color',
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent/highlight color', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='error_color',
            field=models.CharField(default='#ef4444', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h1_size',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='H1 size in rem (e.g., 3.0 = 3rem = 48px with 16px base)', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h2_size',
            field=models.DecimalField(decimal_places=1, default=2.5, help_text='H2 size in rem', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h3_size',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='H3 size in rem', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h4_size',
            field=models.DecimalField(decimal_places=1, default=1.5, help_text='H4 size in rem', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h5_size',
            field=models.DecimalField(decimal_places=1, default=1.25, help_text='H5 size in rem', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='h6_size',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='H6 size in rem', max_digits=3),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='info_color',
            field=models.CharField(default='#3b82f6', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='input_radius',
            field=models.PositiveSmallIntegerField(default=6, help_text='Form inputs border radius'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='letter_spacing',
            field=models.CharField(choices=[('normal', 'Normal'), ('-1px', '-1px (Tight)'), ('-0.5px', '-0.5px'), ('0.5px', '0.5px'), ('1px', '1px (Wide)'), ('2px', '2px')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='line_height',
            field=models.FloatField(choices=[(1.2, '1.2 (Tight)'), (1.4, '1.4'), (1.5, '1.5 (Default)'), (1.6, '1.6'), (1.8, '1.8 (Relaxed)')], default=1.5),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary action color', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', help_text='Secondary accent color', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_2xl',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=64),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_lg',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=32),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_md',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_sm',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=8),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_xl',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=48),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='spacing_xs',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=4),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='success_color',
            field=models.CharField(default='#10b981', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='surface_variant_color',
            field=models.CharField(default='#e5e7eb', help_text='Secondary surface color', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='text_on_brand_color',
            field=models.CharField(default='#ffffff', help_text='Text color on brand/primary backgrounds', max_length=16),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='warning_color',
            field=models.CharField(default='#f59e0b', max_length=16),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='base_font_size',
            field=models.PositiveSmallIntegerField(choices=[(14, '14px'), (16, '16px (Default)'), (18, '18px'), (20, '20px')], default=16),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='body_font',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('Source Sans Pro', 'Source Sans Pro')], default='Nunito', max_length=120),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='heading_font',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('Source Sans Pro', 'Source Sans Pro')], default='Poppins', max_length=120),
        ),
    ]
