# Generated by Django 6.0.6 on 2026-06-13 23:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_muted_text_color_designsystemsettings_text_muted_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeature',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_testimonial_quote',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
