# Generated by Django 6.0.6 on 2026-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_designsystemsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
    ]
