# Generated by Django 6.0.6 on 2026-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_clients_vertical_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsystemsettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent/highlight color', max_length=16, verbose_name='Accent'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=16, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='brand_color',
            field=models.CharField(default='#4f46e5', max_length=16, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='error_color',
            field=models.CharField(default='#ef4444', max_length=16, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='info_color',
            field=models.CharField(default='#3b82f6', max_length=16, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary action color', max_length=16, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', help_text='Secondary accent color', max_length=16, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='success_color',
            field=models.CharField(default='#10b981', max_length=16, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='surface_color',
            field=models.CharField(default='#f8f9fa', max_length=16, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='surface_variant_color',
            field=models.CharField(default='#e5e7eb', help_text='Secondary surface color', max_length=16, verbose_name='Surface variant'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_color',
            field=models.CharField(default='#111827', max_length=16, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_muted_color',
            field=models.CharField(default='#667085', max_length=16, verbose_name='Muted'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_on_brand_color',
            field=models.CharField(default='#ffffff', help_text='Text color on brand/primary backgrounds', max_length=16, verbose_name='On brand'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='warning_color',
            field=models.CharField(default='#f59e0b', max_length=16, verbose_name='Warning'),
        ),
    ]
