# Generated by Django 6.0.6 on 2026-06-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_designsystemsettings_button_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='button_shape',
        ),
    ]
