# Generated by Django 6.0.6 on 2026-06-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_designsystemsettings_button_border_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients_section_height',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full height')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_section_height',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full height')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_section_height',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full height')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_height',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full height')], default='normal', max_length=16, verbose_name='Section height'),
        ),
    ]
