# Generated by Django 6.0.6 on 2026-06-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_migrate_section_height_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height'),
        ),
    ]
