# Generated by Django 6.0.6 on 2026-06-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_seed_color_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortheme',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Feature icons and highlights.', max_length=16, verbose_name='Accent'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Page and section background.', max_length=16, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='brand_color',
            field=models.CharField(blank=True, default='', help_text='Brand identity color.', max_length=16, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='error_color',
            field=models.CharField(blank=True, default='', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='info_color',
            field=models.CharField(blank=True, default='', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='overlay_color',
            field=models.CharField(blank=True, default='', help_text='Hero background image overlay.', max_length=16, verbose_name='Overlay color'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Primary action button color.', max_length=16, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='secondary_color',
            field=models.CharField(blank=True, default='', help_text='Secondary button color.', max_length=16, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='success_color',
            field=models.CharField(blank=True, default='', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='surface_color',
            field=models.CharField(blank=True, default='', help_text='Media placeholders and cards.', max_length=16, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='surface_variant_color',
            field=models.CharField(blank=True, default='', help_text='Borders and dividers.', max_length=16, verbose_name='Surface variant'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='text_color',
            field=models.CharField(blank=True, default='', help_text='Body and heading text.', max_length=16, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='text_muted_color',
            field=models.CharField(blank=True, default='', help_text='Secondary/description text.', max_length=16, verbose_name='Muted'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='text_on_brand_color',
            field=models.CharField(blank=True, default='', help_text='Text on brand backgrounds.', max_length=16, verbose_name='On brand'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='warning_color',
            field=models.CharField(blank=True, default='', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Warning'),
        ),
    ]
