# Generated by Django 6.0.6 on 2026-06-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_designsystemsettings_accent_color_and_more'),
    ]

    operations = [
    ]
