# Generated by Django 6.0.6 on 2026-06-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_designsystemsettings_global_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients_theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Clients color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='CTA color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Features color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Hero color theme'),
        ),
    ]
