# Generated by Django 6.0.6 on 2026-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_seed_10_color_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colortheme',
            name='is_default',
            field=models.BooleanField(default=False, editable=False, verbose_name='Default site theme'),
        ),
    ]
