# Generated by Django 6.0.6 on 2026-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_colortheme_overlay_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortheme',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='button_border_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='error_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='surface_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='surface_variant_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='text_muted_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='text_on_brand_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='warning_color',
        ),
        migrations.AddField(
            model_name='colortheme',
            name='body_text_color',
            field=models.CharField(blank=True, default='', help_text='Paragraphs, copy, and general body content.', max_length=16, verbose_name='Body text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='brand_glow',
            field=models.CharField(blank=True, default='', help_text='Hero centered radial gradient spot.', max_length=16, verbose_name='Brand glow'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='button_primary_bg',
            field=models.CharField(blank=True, default='', help_text='Main call-to-action button background.', max_length=16, verbose_name='Primary button'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='button_primary_hover',
            field=models.CharField(blank=True, default='', help_text='Primary button on hover.', max_length=16, verbose_name='Primary button hover'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='button_secondary_border',
            field=models.CharField(blank=True, default='', help_text='Secondary outline button border and text.', max_length=16, verbose_name='Secondary button'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='button_secondary_hover_bg',
            field=models.CharField(blank=True, default='', help_text='Secondary button fill on hover.', max_length=16, verbose_name='Secondary button hover bg'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='check_color',
            field=models.CharField(blank=True, default='', help_text='Checklist checkmarks.', max_length=16, verbose_name='Checklist color'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='feature_icon_bg',
            field=models.CharField(blank=True, default='', help_text='Feature section icon backgrounds.', max_length=16, verbose_name='Feature icon bg'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='feature_icon_text',
            field=models.CharField(blank=True, default='', help_text='Text inside feature icons.', max_length=16, verbose_name='Feature icon text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='heading_text_color',
            field=models.CharField(blank=True, default='', help_text='H1–H6 and display headings.', max_length=16, verbose_name='Heading text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='link_color',
            field=models.CharField(blank=True, default='', help_text='Text links, announcement links, eyebrow links.', max_length=16, verbose_name='Link text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Link text on hover.', max_length=16, verbose_name='Link hover'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='muted_text_color',
            field=models.CharField(blank=True, default='', help_text='Secondary paragraphs, lead text, announcements.', max_length=16, verbose_name='Muted text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='page_bg',
            field=models.CharField(blank=True, default='', help_text='Body and section background.', max_length=16, verbose_name='Page background'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='surface_bg',
            field=models.CharField(blank=True, default='', help_text='Media placeholders, card fills.', max_length=16, verbose_name='Surface background'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='surface_border',
            field=models.CharField(blank=True, default='', help_text='Card borders, grid lines, dividers, media frames.', max_length=16, verbose_name='Surface border'),
        ),
    ]
