from django.db import migrations

THEMES = [
    {"name": "Default"},
    {
        "name": "Dark",
        "body_text_color": "#f1f5f9",
        "heading_text_color": "#f8fafc",
        "muted_text_color": "#94a3b8",
        "link_color": "#818cf8",
        "link_hover_color": "#a5b4fc",
        "button_primary_bg": "#818cf8",
        "button_primary_hover": "#a5b4fc",
        "button_secondary_border": "#64748b",
        "button_secondary_hover_bg": "#64748b",
        "page_bg": "#0f172a",
        "surface_bg": "#1e293b",
        "surface_border": "#334155",
        "feature_icon_bg": "#f472b6",
        "feature_icon_text": "#0f172a",
        "check_color": "#f472b6",
        "brand_glow": "#818cf8",
    },
    {
        "name": "Forest",
        "body_text_color": "#052e16",
        "heading_text_color": "#022c22",
        "muted_text_color": "#4a7c59",
        "link_color": "#059669",
        "link_hover_color": "#047857",
        "button_primary_bg": "#059669",
        "button_primary_hover": "#047857",
        "button_secondary_border": "#65a30d",
        "button_secondary_hover_bg": "#65a30d",
        "page_bg": "#f0fdf4",
        "surface_bg": "#dcfce7",
        "surface_border": "#bbf7d0",
        "feature_icon_bg": "#fbbf24",
        "feature_icon_text": "#022c22",
        "check_color": "#fbbf24",
        "brand_glow": "#059669",
    },
    {
        "name": "Ocean",
        "body_text_color": "#083344",
        "heading_text_color": "#042f2e",
        "muted_text_color": "#3b82a0",
        "link_color": "#0891b2",
        "link_hover_color": "#0e7490",
        "button_primary_bg": "#0891b2",
        "button_primary_hover": "#0e7490",
        "button_secondary_border": "#06b6d4",
        "button_secondary_hover_bg": "#06b6d4",
        "page_bg": "#ecfeff",
        "surface_bg": "#cffafe",
        "surface_border": "#a5f3fc",
        "feature_icon_bg": "#2dd4bf",
        "feature_icon_text": "#083344",
        "check_color": "#2dd4bf",
        "brand_glow": "#0891b2",
    },
    {
        "name": "Sunset",
        "body_text_color": "#431407",
        "heading_text_color": "#3a0a04",
        "muted_text_color": "#9a5b3a",
        "link_color": "#ea580c",
        "link_hover_color": "#c2410c",
        "button_primary_bg": "#ea580c",
        "button_primary_hover": "#c2410c",
        "button_secondary_border": "#f97316",
        "button_secondary_hover_bg": "#f97316",
        "page_bg": "#fff7ed",
        "surface_bg": "#ffedd5",
        "surface_border": "#fed7aa",
        "feature_icon_bg": "#facc15",
        "feature_icon_text": "#431407",
        "check_color": "#facc15",
        "brand_glow": "#ea580c",
    },
    {
        "name": "Lavender",
        "body_text_color": "#2e1065",
        "heading_text_color": "#1e0a4a",
        "muted_text_color": "#7c4fa0",
        "link_color": "#7c3aed",
        "link_hover_color": "#6d28d9",
        "button_primary_bg": "#7c3aed",
        "button_primary_hover": "#6d28d9",
        "button_secondary_border": "#a78bfa",
        "button_secondary_hover_bg": "#a78bfa",
        "page_bg": "#faf5ff",
        "surface_bg": "#f3e8ff",
        "surface_border": "#e9d5ff",
        "feature_icon_bg": "#f472b6",
        "feature_icon_text": "#2e1065",
        "check_color": "#f472b6",
        "brand_glow": "#7c3aed",
    },
    {
        "name": "Crimson",
        "body_text_color": "#450a0a",
        "heading_text_color": "#380707",
        "muted_text_color": "#a04040",
        "link_color": "#dc2626",
        "link_hover_color": "#b91c1c",
        "button_primary_bg": "#dc2626",
        "button_primary_hover": "#b91c1c",
        "button_secondary_border": "#ef4444",
        "button_secondary_hover_bg": "#ef4444",
        "page_bg": "#fef2f2",
        "surface_bg": "#fee2e2",
        "surface_border": "#fecaca",
        "feature_icon_bg": "#facc15",
        "feature_icon_text": "#450a0a",
        "check_color": "#facc15",
        "brand_glow": "#dc2626",
    },
    {
        "name": "Slate",
        "body_text_color": "#0f172a",
        "heading_text_color": "#020617",
        "muted_text_color": "#64748b",
        "link_color": "#475569",
        "link_hover_color": "#334155",
        "button_primary_bg": "#475569",
        "button_primary_hover": "#334155",
        "button_secondary_border": "#64748b",
        "button_secondary_hover_bg": "#64748b",
        "page_bg": "#f8fafc",
        "surface_bg": "#f1f5f9",
        "surface_border": "#e2e8f0",
        "feature_icon_bg": "#94a3b8",
        "feature_icon_text": "#0f172a",
        "check_color": "#94a3b8",
        "brand_glow": "#475569",
    },
    {
        "name": "Amber",
        "body_text_color": "#451a03",
        "heading_text_color": "#361203",
        "muted_text_color": "#926d28",
        "link_color": "#d97706",
        "link_hover_color": "#b45309",
        "button_primary_bg": "#d97706",
        "button_primary_hover": "#b45309",
        "button_secondary_border": "#f59e0b",
        "button_secondary_hover_bg": "#f59e0b",
        "page_bg": "#fffbeb",
        "surface_bg": "#fef3c7",
        "surface_border": "#fde68a",
        "feature_icon_bg": "#fbbf24",
        "feature_icon_text": "#451a03",
        "check_color": "#fbbf24",
        "brand_glow": "#d97706",
    },
    {
        "name": "Mint",
        "body_text_color": "#022c22",
        "heading_text_color": "#021c15",
        "muted_text_color": "#3b7970",
        "link_color": "#0d9488",
        "link_hover_color": "#0f766e",
        "button_primary_bg": "#0d9488",
        "button_primary_hover": "#0f766e",
        "button_secondary_border": "#14b8a6",
        "button_secondary_hover_bg": "#14b8a6",
        "page_bg": "#f0fdfa",
        "surface_bg": "#ccfbf1",
        "surface_border": "#99f6e4",
        "feature_icon_bg": "#a3e635",
        "feature_icon_text": "#022c22",
        "check_color": "#a3e635",
        "brand_glow": "#0d9488",
    },
    {
        "name": "Rose",
        "body_text_color": "#4c0519",
        "heading_text_color": "#3b0313",
        "muted_text_color": "#a8455a",
        "link_color": "#e11d48",
        "link_hover_color": "#be123c",
        "button_primary_bg": "#e11d48",
        "button_primary_hover": "#be123c",
        "button_secondary_border": "#f43f5e",
        "button_secondary_hover_bg": "#f43f5e",
        "page_bg": "#fff1f2",
        "surface_bg": "#ffe4e6",
        "surface_border": "#fecdd3",
        "feature_icon_bg": "#fbbf24",
        "feature_icon_text": "#4c0519",
        "check_color": "#fbbf24",
        "brand_glow": "#e11d48",
    },
    {
        "name": "Copper",
        "body_text_color": "#292524",
        "heading_text_color": "#1c1917",
        "muted_text_color": "#78716c",
        "link_color": "#b45309",
        "link_hover_color": "#92400e",
        "button_primary_bg": "#b45309",
        "button_primary_hover": "#92400e",
        "button_secondary_border": "#d97706",
        "button_secondary_hover_bg": "#d97706",
        "page_bg": "#fefce8",
        "surface_bg": "#fef9c3",
        "surface_border": "#fef08a",
        "feature_icon_bg": "#f59e0b",
        "feature_icon_text": "#292524",
        "check_color": "#f59e0b",
        "brand_glow": "#b45309",
    },
]

ALL_THEME_NAMES = [t["name"] for t in THEMES]


def seed_themes(apps, schema_editor):
    ColorTheme = apps.get_model("home", "ColorTheme")
    ColorTheme.objects.all().delete()
    for data in THEMES:
        ColorTheme.objects.create(**data)
    # Mark Default as is_default
    ColorTheme.objects.filter(name="Default").update(is_default=True)


def reverse_seed(apps, schema_editor):
    ColorTheme = apps.get_model("home", "ColorTheme")
    ColorTheme.objects.filter(name__in=ALL_THEME_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_remove_colortheme_accent_color_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_themes, reverse_seed),
    ]
