# Generated by Django 6.0.6 on 2026-06-15 09:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_reseed_themes_component_colors'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='colortheme',
            name='footer_bg',
            field=models.CharField(blank=True, default='', help_text='Footer background.', max_length=16, verbose_name='Footer background'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='footer_heading_color',
            field=models.CharField(blank=True, default='', help_text='Footer column headings.', max_length=16, verbose_name='Footer heading'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='footer_link_color',
            field=models.CharField(blank=True, default='', help_text='Footer links.', max_length=16, verbose_name='Footer link'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='footer_link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Footer links on hover.', max_length=16, verbose_name='Footer link hover'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='footer_text_color',
            field=models.CharField(blank=True, default='', help_text='Footer body text.', max_length=16, verbose_name='Footer text'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='navbar_bg',
            field=models.CharField(blank=True, default='', help_text='Navbar bar background.', max_length=16, verbose_name='Navbar background'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='navbar_link_color',
            field=models.CharField(blank=True, default='', help_text='Navbar navigation links.', max_length=16, verbose_name='Navbar link'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='navbar_link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Navbar links on hover.', max_length=16, verbose_name='Navbar link hover'),
        ),
        migrations.AddField(
            model_name='colortheme',
            name='navbar_text_color',
            field=models.CharField(blank=True, default='', help_text='Navbar text and brand.', max_length=16, verbose_name='Navbar text'),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='Site name', max_length=120, verbose_name='Brand name')),
                ('brand_description', models.TextField(blank=True, help_text='Short description of the brand, shown in the first column.', verbose_name='Brand description')),
                ('col1_heading', models.CharField(blank=True, default='Product', max_length=80)),
                ('col2_heading', models.CharField(blank=True, default='Company', max_length=80)),
                ('col3_heading', models.CharField(blank=True, default='Resources', max_length=80)),
                ('copyright_text', models.CharField(blank=True, default='All rights reserved.', max_length=255, verbose_name='Copyright text')),
                ('footer_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Footer color theme')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer settings',
                'verbose_name_plural': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn3Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_col3_links', to='home.footersettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn2Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_col2_links', to='home.footersettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn1Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_col1_links', to='home.footersettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(blank=True, default='Site name', help_text='Shown as text logo when no image is set.', max_length=120, verbose_name='Logo text')),
                ('sticky', models.BooleanField(default=False, help_text='Keep the navbar fixed at the top when scrolling.', verbose_name='Sticky navbar')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='CTA button label')),
                ('cta_url', models.CharField(blank=True, max_length=255, verbose_name='CTA button URL')),
                ('logo', models.ForeignKey(blank=True, help_text='Upload a logo image. If empty, logo_text is shown as text logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo image')),
                ('navbar_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Navbar color theme')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navbar settings',
                'verbose_name_plural': 'Navbar settings',
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='home.navbarsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g., Twitter, GitHub', max_length=40)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-twitter-x). Optional.', max_length=40)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.footersettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
