# Generated by Django 6.0.6 on 2026-06-15 14:13

import django.db.models.deletion
from django.db import migrations, models


def migrate_navbar_links(apps, schema_editor):
    NavbarSettings = apps.get_model("home", "NavbarSettings")
    NavigationLinkGroup = apps.get_model("home", "NavigationLinkGroup")
    NavigationLink = apps.get_model("home", "NavigationLink")
    NavbarLink = apps.get_model("home", "NavbarLink")

    for ns in NavbarSettings.objects.all():
        links = list(NavbarLink.objects.filter(settings=ns))
        if not links:
            continue
        group = NavigationLinkGroup.objects.create(
            name=f"Navbar (site {ns.site_id})"
        )
        for link in links:
            NavigationLink.objects.create(
                group=group,
                sort_order=link.sort_order or 0,
                label=link.label,
                url=link.url,
            )
        ns.nav_group = group
        ns.save(update_fields=["nav_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_footersettings_columns_delete_footercolumn"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbarsettings",
            name="nav_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.navigationlinkgroup",
                verbose_name="Navigation links",
            ),
        ),
        migrations.RunPython(migrate_navbar_links, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="NavbarLink",
        ),
    ]
