# Generated by Django 6.0.6 on 2026-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_navbarsettings_cta_label_navbarsettings_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='anchor_id',
            field=models.CharField(blank=True, default='header', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Content width'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16, verbose_name='Text alignment'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
    ]
