# Generated by Django 6.0.6 on 2026-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_navbar_transparent_and_scroll_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_variant',
            field=models.CharField(choices=[('filled', 'Filled'), ('outline', 'Outline')], default='filled', max_length=10, verbose_name='Icon style'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('threads', 'Threads'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('quora', 'Quora'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('line', 'LINE'), ('tumblr', 'Tumblr'), ('medium', 'Medium'), ('github', 'GitHub'), ('substack', 'Substack')], default='github', max_length=20, verbose_name='Platform'),
        ),
    ]
