# Generated by Django 6.0.6 on 2026-06-16 18:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_designsystemsettings_global_theme_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('header_layout', models.CharField(choices=[('centered', 'Centered'), ('simple', 'Simple'), ('with_stats', 'With stats'), ('with_cards', 'With cards'), ('background_image', 'Background image')], default='centered', max_length=40, verbose_name='Layout')),
                ('header_anchor_id', models.CharField(blank=True, default='service-header', max_length=40, verbose_name='Anchor ID')),
                ('header_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='spacious', max_length=16, verbose_name='Section height')),
                ('header_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width')),
                ('header_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment')),
                ('header_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('header_eyebrow', models.CharField(blank=True, max_length=80)),
                ('header_title', models.CharField(blank=True, max_length=180)),
                ('header_description', wagtail.fields.RichTextField(blank=True)),
                ('header_primary_button_label', models.CharField(blank=True, max_length=80)),
                ('header_primary_button_url', models.CharField(blank=True, max_length=255)),
                ('header_secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('header_secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('header_image_alt', models.CharField(blank=True, max_length=120)),
                ('header_overlay_color', models.CharField(blank=True, default='#0f172a', max_length=16, verbose_name='Overlay color')),
                ('header_overlay_opacity', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=70, null=True, verbose_name='Overlay opacity')),
                ('content_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('content_layout', models.CharField(choices=[('centered', 'Centered'), ('split_image', 'Split with image'), ('two_column', 'Two columns'), ('with_testimonial', 'With testimonial'), ('with_stats', 'With stats')], default='split_image', max_length=40, verbose_name='Layout')),
                ('content_anchor_id', models.CharField(blank=True, default='service-content', max_length=40, verbose_name='Anchor ID')),
                ('content_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height')),
                ('content_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width')),
                ('content_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16, verbose_name='Horizontal alignment')),
                ('content_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('content_eyebrow', models.CharField(blank=True, max_length=80)),
                ('content_title', models.CharField(blank=True, max_length=180)),
                ('content_description', wagtail.fields.RichTextField(blank=True)),
                ('content_body', wagtail.fields.RichTextField(blank=True)),
                ('content_image_alt', models.CharField(blank=True, max_length=120)),
                ('content_testimonial_quote', wagtail.fields.RichTextField(blank=True)),
                ('content_testimonial_name', models.CharField(blank=True, max_length=100)),
                ('content_testimonial_role', models.CharField(blank=True, max_length=120)),
                ('services_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('services_layout', models.CharField(choices=[('service_grid', 'Service grid'), ('service_cards', 'Service cards'), ('service_profiles', 'Profile cards'), ('split_service_list', 'Split service list')], default='service_grid', max_length=40, verbose_name='Layout')),
                ('services_anchor_id', models.CharField(blank=True, default='services', max_length=40, verbose_name='Anchor ID')),
                ('services_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height')),
                ('services_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='wide', max_length=16, verbose_name='Section width')),
                ('services_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment')),
                ('services_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('services_eyebrow', models.CharField(blank=True, max_length=80)),
                ('services_title', models.CharField(blank=True, max_length=180)),
                ('services_description', wagtail.fields.RichTextField(blank=True)),
                ('content_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('content_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Content color theme')),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('header_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Header color theme')),
                ('services_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Services color theme')),
            ],
            options={
                'verbose_name': 'Service page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePageServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=120)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='home.servicepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.servicepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
