# Generated by Django 6.0.6 on 2026-06-17 06:24

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_servicedetailpage_servicedetailfeature_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('header_layout', models.CharField(choices=[('centered', 'Centered'), ('simple', 'Simple'), ('with_stats', 'With stats'), ('background_image', 'Background image')], default='centered', max_length=40, verbose_name='Layout')),
                ('header_anchor_id', models.CharField(blank=True, default='blog-header', max_length=40, verbose_name='Anchor ID')),
                ('header_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height')),
                ('header_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width')),
                ('header_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment')),
                ('header_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('header_eyebrow', models.CharField(blank=True, max_length=80)),
                ('header_title', models.CharField(blank=True, max_length=180)),
                ('header_description', wagtail.fields.RichTextField(blank=True)),
                ('header_primary_button_label', models.CharField(blank=True, max_length=80)),
                ('header_primary_button_url', models.CharField(blank=True, max_length=255)),
                ('header_secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('header_secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('header_image_alt', models.CharField(blank=True, max_length=120)),
                ('header_overlay_color', models.CharField(blank=True, default='#0f172a', max_length=16, verbose_name='Overlay color')),
                ('header_overlay_opacity', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=70, null=True, verbose_name='Overlay opacity')),
                ('blog_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('blog_layout', models.CharField(choices=[('three_column', 'Three column'), ('three_column_images', 'Three column with images'), ('background_images', 'Background image cards'), ('single_column', 'Single column'), ('single_column_images', 'Single column with images'), ('featured_post', 'With featured post'), ('photo_list', 'With photo and list')], default='three_column_images', max_length=40, verbose_name='Layout')),
                ('blog_anchor_id', models.CharField(blank=True, default='articles', max_length=40, verbose_name='Anchor ID')),
                ('blog_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='normal', max_length=16, verbose_name='Section height')),
                ('blog_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='wide', max_length=16, verbose_name='Section width')),
                ('blog_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16, verbose_name='Horizontal alignment')),
                ('blog_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('blog_eyebrow', models.CharField(blank=True, max_length=80)),
                ('blog_title', models.CharField(blank=True, max_length=180)),
                ('blog_description', wagtail.fields.RichTextField(blank=True)),
                ('cta_enabled', models.BooleanField(default=True, verbose_name='Section enabled')),
                ('cta_layout', models.CharField(choices=[('left_stack', 'Left stacked'), ('centered', 'Centered'), ('horizontal_split', 'Horizontal split'), ('media_left', 'Media left')], default='centered', max_length=40, verbose_name='Layout')),
                ('cta_anchor_id', models.CharField(blank=True, default='subscribe', max_length=40, verbose_name='Anchor ID')),
                ('cta_section_height', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='compact', max_length=16, verbose_name='Section height')),
                ('cta_content_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width')),
                ('cta_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment')),
                ('cta_vertical_alignment', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment')),
                ('cta_eyebrow', models.CharField(blank=True, max_length=80)),
                ('cta_title', models.CharField(blank=True, max_length=180)),
                ('cta_description', wagtail.fields.RichTextField(blank=True)),
                ('cta_primary_button_label', models.CharField(blank=True, max_length=80)),
                ('cta_primary_button_url', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('cta_image_alt', models.CharField(blank=True, max_length=120)),
                ('blog_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Blog index color theme')),
                ('cta_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('cta_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='CTA color theme')),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('header_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Header color theme')),
            ],
            options={
                'verbose_name': 'Blog index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=160)),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=120)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_items', to='home.blogindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
