# Generated by Django 6.0.6 on 2026-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_colortheme_body_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='header_overlay_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=32, verbose_name='Overlay color'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='button_border_color',
            field=models.CharField(default='#4f46e5', help_text='Border color for outlined buttons', max_length=32, verbose_name='Button border color'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='overlay_color',
            field=models.CharField(default='#ffffff', help_text='Color for the image overlay. Applied to: hero background image overlay.', max_length=32, verbose_name='Overlay color'),
        ),
        migrations.AlterField(
            model_name='servicedetailpage',
            name='header_overlay_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=32, verbose_name='Overlay color'),
        ),
    ]
