# Generated by Django 6.0.6 on 2026-06-17 17:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


CLIENTS_HEADING = "Pengalaman kami terbentuk dari berbagai project dan lingkungan bisnis."
CLIENTS = [
    ("client", {"name": "Company 1"}),
    ("client", {"name": "Company 2"}),
    ("client", {"name": "Company 3"}),
    ("client", {"name": "Company 4"}),
    ("client", {"name": "Company 5"}),
]


def seed_home_clients(apps, schema_editor):
    KoderstoryHomePage = apps.get_model("home", "KoderstoryHomePage")
    for page in KoderstoryHomePage.objects.all():
        changed = False
        if not page.clients_heading:
            page.clients_heading = CLIENTS_HEADING
            changed = True
        if not page.clients:
            page.clients = CLIENTS
            changed = True
        if page.content_enabled:
            page.content_enabled = False
            changed = True
        if changed:
            page.save()


def reverse_seed_home_clients(apps, schema_editor):
    KoderstoryHomePage = apps.get_model("home", "KoderstoryHomePage")
    KoderstoryHomePage.objects.update(content_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_seed_koderstory_dark_flat_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients',
            field=wagtail.fields.StreamField([('client', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('url', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_anchor_id',
            field=models.CharField(blank=True, default='clients', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_enabled',
            field=models.BooleanField(default=True, verbose_name='Section enabled'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_layout',
            field=models.CharField(choices=[('bootstrap_dark_flat', 'Bootstrap dark flat')], default='bootstrap_dark_flat', max_length=40, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Spacious'), ('full', 'Full')], default='compact', max_length=16, verbose_name='Section height'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Client color theme'),
        ),
        migrations.AddField(
            model_name='koderstoryhomepage',
            name='clients_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
        migrations.RunPython(seed_home_clients, reverse_seed_home_clients),
    ]
