# Generated by Django 6.0.6 on 2026-06-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homefeature_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designsystemsettings',
            options={'verbose_name': 'Global settings', 'verbose_name_plural': 'Global settings'},
        ),
    ]
