# Generated by Django 6.0.6 on 2026-06-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_designsystemsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_border_color',
            field=models.CharField(default='#4f46e5', help_text='Border color for outlined buttons', max_length=16, verbose_name='Button border color'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_border_width',
            field=models.PositiveSmallIntegerField(default=1, help_text='Button border width in pixels (0-5)'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_color',
            field=models.CharField(default='#4f46e5', help_text='Button background color (defaults to brand)', max_length=16, verbose_name='Button color'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_padding_x',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=24, verbose_name='Button horizontal padding'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_padding_y',
            field=models.PositiveSmallIntegerField(choices=[(4, '4px (XS)'), (8, '8px (SM)'), (16, '16px (MD)'), (24, '24px'), (32, '32px (LG)'), (48, '48px (XL)'), (64, '64px (2XL)')], default=8, verbose_name='Button vertical padding'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='button_shape',
            field=models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('pill', 'Pill')], default='round', help_text='Button shape: Square (sharp corners), Round (uses border radius), Pill (fully rounded)', max_length=10),
        ),
    ]
