# Generated by Django 6.0.6 on 2026-06-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_designsystemsettings_button_border_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='button_color',
        ),
    ]
