# Generated by Django 6.0.6 on 2026-06-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_designsystemsettings_button_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients_anchor_id',
            field=models.CharField(blank=True, default='clients', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_enabled',
            field=models.BooleanField(default=True, verbose_name='Section enabled'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_layout',
            field=models.CharField(choices=[('centered_heading_row', 'Centered heading with logo row'), ('row_cta', 'Logo row with CTA'), ('left_heading_row', 'Left heading with logo row'), ('split_copy_grid', 'Split copy with logo grid'), ('bordered_grid', 'Bordered logo grid')], default='centered_heading_row', max_length=40, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_anchor_id',
            field=models.CharField(blank=True, default='cta', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_enabled',
            field=models.BooleanField(default=True, verbose_name='Section enabled'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_layout',
            field=models.CharField(choices=[('left_stack', 'Left stacked'), ('centered', 'Centered'), ('horizontal_split', 'Horizontal split'), ('media_left', 'Media left')], default='left_stack', max_length=40, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16, verbose_name='Horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_anchor_id',
            field=models.CharField(blank=True, default='features', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_enabled',
            field=models.BooleanField(default=True, verbose_name='Section enabled'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_layout',
            field=models.CharField(choices=[('list_media_right', 'Feature list with media right'), ('centered_two_column', 'Centered two-column grid'), ('media_grid', 'Media with feature grid'), ('heading_media_below', 'Heading with media below'), ('centered_three_column', 'Centered three-column grid'), ('media_left_list', 'Media left with feature list'), ('card_columns', 'Three-column feature cards'), ('split_media_list', 'Split media with feature list'), ('split_media_testimonial', 'Split media with testimonial'), ('heading_left_grid', 'Heading left with feature grid'), ('intro_checklist', 'Intro with checklist grid'), ('feature_grid', 'Feature grid')], default='list_media_right', max_length=40, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='large', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16, verbose_name='Horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_anchor_id',
            field=models.CharField(blank=True, default='hero', max_length=40, verbose_name='Anchor ID'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide'), ('full', 'Full width')], default='normal', max_length=16, verbose_name='Section width'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_enabled',
            field=models.BooleanField(default=True, verbose_name='Section enabled'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_layout',
            field=models.CharField(choices=[('centered_simple', 'Centered simple'), ('split_media_right', 'Split media right'), ('background_media', 'Background media'), ('centered_media_below', 'Centered with media below'), ('half_media_right', 'Half media right'), ('angled_media_right', 'Angled media right')], default='centered_simple', max_length=40, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='large', max_length=16, verbose_name='Section height'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=16, verbose_name='Horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16, verbose_name='Vertical alignment'),
        ),
    ]
