# Generated by Django 6.0.6 on 2026-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_clients_anchor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsystemsettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent/highlight color. Applied to: feature section icon backgrounds and checklist checkmarks.', max_length=16, verbose_name='Accent'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Page background color. Applied to: body background and section backgrounds.', max_length=16, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='brand_color',
            field=models.CharField(default='#4f46e5', help_text='Brand identity color. Applied to: text links, announcement badges, hover states, and the decorative hero spotlight gradient.', max_length=16, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='error_color',
            field=models.CharField(default='#ef4444', help_text='Error state. Applied to: error messages, validation alerts, and destructive indicators.', max_length=16, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='info_color',
            field=models.CharField(default='#3b82f6', help_text='Informational state. Applied to: info banners, notification badges, and neutral indicators.', max_length=16, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary action color. Applied to: main call-to-action buttons (btn-primary) as their background.', max_length=16, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', help_text='Secondary action color. Applied to: secondary/outline buttons (btn-secondary) as their border and text, and fills on hover.', max_length=16, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='success_color',
            field=models.CharField(default='#10b981', help_text='Success state. Applied to: success messages, confirmation badges, and positive indicators.', max_length=16, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='surface_color',
            field=models.CharField(default='#f8f9fa', help_text='Surface/elevated background. Applied to: media placeholder backgrounds, card subtle fills.', max_length=16, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='surface_variant_color',
            field=models.CharField(default='#e5e7eb', help_text='Secondary surface color. Applied to: borders, dividers, grid lines, and subtle UI accents.', max_length=16, verbose_name='Surface variant'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_color',
            field=models.CharField(default='#111827', help_text='Primary text color. Applied to: all body copy, headings, and page text content.', max_length=16, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_muted_color',
            field=models.CharField(default='#667085', help_text='Secondary/muted text color. Applied to: description paragraphs, secondary info, and helper text.', max_length=16, verbose_name='Muted'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='text_on_brand_color',
            field=models.CharField(default='#ffffff', help_text='Text color placed on brand-colored backgrounds. Applied to: icon text on feature badges.', max_length=16, verbose_name='On brand'),
        ),
        migrations.AlterField(
            model_name='designsystemsettings',
            name='warning_color',
            field=models.CharField(default='#f59e0b', help_text='Warning state. Applied to: warning messages, alert banners, and caution indicators.', max_length=16, verbose_name='Warning'),
        ),
    ]
