# Generated by Django 6.0.6 on 2026-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_designsystemsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsystemsettings',
            name='button_border_width',
            field=models.PositiveSmallIntegerField(choices=[(0, '0px'), (1, '1px'), (2, '2px'), (3, '3px'), (4, '4px'), (5, '5px')], default=1, help_text='Button border width in pixels (0-5)'),
        ),
    ]
