# Generated by Django 6.0.6 on 2026-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remap_section_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystemsettings',
            name='overlay_color',
            field=models.CharField(default='#ffffff', help_text='Color for the image overlay. Applied to: hero background image overlay.', max_length=16, verbose_name='Overlay color'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=75, help_text='Opacity percentage for the image overlay (0 = transparent, 100 = solid).', verbose_name='Overlay opacity'),
        ),
    ]
