# Generated by Django 6.0.6 on 2026-06-15 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_designsystemsettings_overlay_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('brand_color', models.CharField(blank=True, default='#4f46e5', help_text='Brand identity color.', max_length=16, verbose_name='Brand')),
                ('primary_color', models.CharField(blank=True, default='#3b82f6', help_text='Primary action button color.', max_length=16, verbose_name='Primary')),
                ('secondary_color', models.CharField(blank=True, default='#8b5cf6', help_text='Secondary button color.', max_length=16, verbose_name='Secondary')),
                ('accent_color', models.CharField(blank=True, default='#f59e0b', help_text='Feature icons and highlights.', max_length=16, verbose_name='Accent')),
                ('success_color', models.CharField(blank=True, default='#10b981', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Success')),
                ('warning_color', models.CharField(blank=True, default='#f59e0b', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Warning')),
                ('error_color', models.CharField(blank=True, default='#ef4444', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Error')),
                ('info_color', models.CharField(blank=True, default='#3b82f6', help_text='Leave blank to inherit from global settings.', max_length=16, verbose_name='Info')),
                ('background_color', models.CharField(blank=True, default='#ffffff', help_text='Page and section background.', max_length=16, verbose_name='Background')),
                ('surface_color', models.CharField(blank=True, default='#f8f9fa', help_text='Media placeholders and cards.', max_length=16, verbose_name='Surface')),
                ('surface_variant_color', models.CharField(blank=True, default='#e5e7eb', help_text='Borders and dividers.', max_length=16, verbose_name='Surface variant')),
                ('text_color', models.CharField(blank=True, default='#111827', help_text='Body and heading text.', max_length=16, verbose_name='Text')),
                ('text_muted_color', models.CharField(blank=True, default='#667085', help_text='Secondary/description text.', max_length=16, verbose_name='Muted')),
                ('text_on_brand_color', models.CharField(blank=True, default='#ffffff', help_text='Text on brand backgrounds.', max_length=16, verbose_name='On brand')),
                ('overlay_color', models.CharField(blank=True, default='#ffffff', help_text='Hero background image overlay.', max_length=16, verbose_name='Overlay color')),
                ('overlay_opacity', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=None, help_text='Leave blank to inherit from global settings.', null=True, verbose_name='Overlay opacity')),
            ],
            options={
                'verbose_name': 'Color theme',
                'verbose_name_plural': 'Color themes',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Clients color theme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='CTA color theme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Features color theme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Hero color theme'),
        ),
    ]
