# Generated by Django 6.0.6 on 2026-06-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_clear_default_theme_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='error_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='surface_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='surface_variant_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='text_muted_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='text_on_brand_color',
        ),
        migrations.RemoveField(
            model_name='designsystemsettings',
            name='warning_color',
        ),
        migrations.AddField(
            model_name='colortheme',
            name='button_border_color',
            field=models.CharField(blank=True, default='', help_text='Border color for buttons.', max_length=16, verbose_name='Button border'),
        ),
        migrations.AddField(
            model_name='designsystemsettings',
            name='global_theme',
            field=models.ForeignKey(blank=True, help_text='Select a color theme for the entire site. Color pickers are available in Snippets → Color themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Color theme'),
        ),
    ]
