# Generated by Django 6.0.6 on 2026-06-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_clean_up_stale_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsystemsettings',
            name='global_theme',
            field=models.ForeignKey(blank=True, default=1, help_text='Select a color theme for the entire site. Color pickers are available in Snippets → Color themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Color theme'),
        ),
    ]
