# Generated by Django 6.0.6 on 2026-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_colortheme_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortheme',
            name='overlay_color',
        ),
        migrations.RemoveField(
            model_name='colortheme',
            name='overlay_opacity',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_overlay_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Color tint for the background image overlay.', max_length=16, verbose_name='Overlay color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_overlay_opacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], default=70, help_text='Transparency of the overlay (0 = transparent, 100 = solid).', null=True, verbose_name='Overlay opacity'),
        ),
    ]
