# Generated by Django 6.0.6 on 2026-06-15 10:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


def migrate_footer_data(apps, schema_editor):
    FooterSettings = apps.get_model("home", "FooterSettings")
    FooterColumn = apps.get_model("home", "FooterColumn")
    FooterColumnLink = apps.get_model("home", "FooterColumnLink")
    FooterColumn1Link = apps.get_model("home", "FooterColumn1Link")
    FooterColumn2Link = apps.get_model("home", "FooterColumn2Link")
    FooterColumn3Link = apps.get_model("home", "FooterColumn3Link")
    SocialLinkModel = apps.get_model("home", "SocialLink")

    for fs in FooterSettings.objects.all():
        sort_order = 0

        # 1. Brand text → "text" column (25%)
        brand_text = (fs.brand_description or "").strip()
        brand_name = (fs.brand_name or "").strip()
        if brand_text or brand_name:
            FooterColumn.objects.create(
                settings=fs,
                sort_order=sort_order,
                column_type="text",
                width=25,
                heading=brand_name,
                body=brand_text,
            )
            sort_order += 1

        # 2. Column 1 → "navigation" column (25%)
        col1_links = FooterColumn1Link.objects.filter(settings=fs)
        heading = (fs.col1_heading or "").strip()
        if heading or col1_links.exists():
            col = FooterColumn.objects.create(
                settings=fs,
                sort_order=sort_order,
                column_type="navigation",
                width=25,
                heading=heading,
            )
            sort_order += 1
            for i, link in enumerate(col1_links.all()):
                FooterColumnLink.objects.create(
                    column=col,
                    sort_order=link.sort_order if link.sort_order is not None else i,
                    label=link.label,
                    url=link.url,
                )

        # 3. Column 2 → "navigation" column (25%)
        col2_links = FooterColumn2Link.objects.filter(settings=fs)
        heading = (fs.col2_heading or "").strip()
        if heading or col2_links.exists():
            col = FooterColumn.objects.create(
                settings=fs,
                sort_order=sort_order,
                column_type="navigation",
                width=25,
                heading=heading,
            )
            sort_order += 1
            for i, link in enumerate(col2_links.all()):
                FooterColumnLink.objects.create(
                    column=col,
                    sort_order=link.sort_order if link.sort_order is not None else i,
                    label=link.label,
                    url=link.url,
                )

        # 4. Column 3 → "navigation" column (25%)
        col3_links = FooterColumn3Link.objects.filter(settings=fs)
        heading = (fs.col3_heading or "").strip()
        if heading or col3_links.exists():
            col = FooterColumn.objects.create(
                settings=fs,
                sort_order=sort_order,
                column_type="navigation",
                width=25,
                heading=heading,
            )
            sort_order += 1
            for i, link in enumerate(col3_links.all()):
                FooterColumnLink.objects.create(
                    column=col,
                    sort_order=link.sort_order if link.sort_order is not None else i,
                    label=link.label,
                    url=link.url,
                )

        # 5. Social links → "social" column (100%)
        social_links = SocialLinkModel.objects.filter(settings=fs)
        if social_links.exists():
            col = FooterColumn.objects.create(
                settings=fs,
                sort_order=sort_order,
                column_type="social",
                width=100,
                heading="Connect",
                icon_size="medium",
                icon_position="left",
            )
            for i, link in enumerate(social_links.all()):
                FooterColumnLink.objects.create(
                    column=col,
                    sort_order=link.sort_order if link.sort_order is not None else i,
                    label=link.label,
                    url=link.url,
                    icon_class=link.icon,
                )


def reverse_migrate(apps, schema_editor):
    FooterColumn = apps.get_model("home", "FooterColumn")
    FooterColumnLink = apps.get_model("home", "FooterColumnLink")
    FooterColumnLink.objects.all().delete()
    FooterColumn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_colortheme_footer_bg_colortheme_footer_heading_color_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        # Step 1: Add new fields to FooterSettings (non-destructive)
        migrations.AddField(
            model_name="footersettings",
            name="anchor_id",
            field=models.CharField(
                blank=True, default="footer", max_length=40, verbose_name="Anchor ID"
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="bottom_bar",
            field=models.BooleanField(
                default=True,
                help_text="Enable the copyright bar at the bottom of the footer.",
                verbose_name="Show bottom bar",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="content_width",
            field=models.CharField(
                choices=[
                    ("narrow", "Narrow"),
                    ("normal", "Normal"),
                    ("wide", "Wide"),
                    ("full", "Full width"),
                ],
                default="normal",
                max_length=16,
                verbose_name="Content width",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="section_height",
            field=models.CharField(
                choices=[
                    ("compact", "Compact"),
                    ("normal", "Normal"),
                    ("spacious", "Spacious"),
                    ("full", "Full"),
                ],
                default="normal",
                max_length=16,
                verbose_name="Section height",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="text_alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=16,
                verbose_name="Text alignment",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="vertical_alignment",
            field=models.CharField(
                choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                default="center",
                max_length=16,
                verbose_name="Vertical alignment",
            ),
        ),
        # Step 2: Create new models
        migrations.CreateModel(
            name="FooterColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("social", "Social"),
                            ("newsletter", "Newsletter"),
                            ("text", "Text"),
                            ("image", "Image"),
                        ],
                        default="navigation",
                        max_length=20,
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (25, "25%"),
                            (33, "33%"),
                            (50, "50%"),
                            (66, "66%"),
                            (75, "75%"),
                            (100, "100%"),
                        ],
                        default=25,
                        help_text="Column width as a percentage of the footer row.",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=80)),
                (
                    "newsletter_description",
                    wagtail.fields.RichTextField(blank=True),
                ),
                ("placeholder_text", models.CharField(blank=True, max_length=80)),
                ("button_label", models.CharField(blank=True, max_length=80)),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        help_text="Form action URL for the newsletter form.",
                        max_length=255,
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "image_height",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Max height in pixels for the image.",
                        null=True,
                        verbose_name="Image height (px)",
                    ),
                ),
                (
                    "image_position",
                    models.CharField(
                        choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                        default="left",
                        max_length=10,
                        verbose_name="Image alignment",
                    ),
                ),
                (
                    "icon_size",
                    models.CharField(
                        choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "icon_position",
                    models.CharField(
                        choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_columns",
                        to="home.footersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FooterColumnLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-twitter-x). Used for social columns.",
                        max_length=40,
                    ),
                ),
                (
                    "column",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_links",
                        to="home.footercolumn",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        # Step 3: Data migration — copy old data into new models
        migrations.RunPython(migrate_footer_data, reverse_migrate),
        # Step 4: Remove old fields (safe after data copy)
        migrations.RemoveField(
            model_name="footersettings",
            name="brand_description",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="col1_heading",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="col2_heading",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="col3_heading",
        ),
        # Step 5: Delete old models
        migrations.DeleteModel(
            name="FooterColumn1Link",
        ),
        migrations.DeleteModel(
            name="FooterColumn2Link",
        ),
        migrations.DeleteModel(
            name="FooterColumn3Link",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
    ]
