# Generated by Django 6.0.6 on 2026-06-15 10:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def migrate_column_links(apps, schema_editor):
    FooterColumn = apps.get_model("home", "FooterColumn")
    NavigationLinkGroup = apps.get_model("home", "NavigationLinkGroup")
    NavigationLink = apps.get_model("home", "NavigationLink")
    SocialMediaGroup = apps.get_model("home", "SocialMediaGroup")
    SocialLink = apps.get_model("home", "SocialLink")
    FooterColumnLink = apps.get_model("home", "FooterColumnLink")

    for col in FooterColumn.objects.all():
        if col.column_type == "navigation":
            links = list(FooterColumnLink.objects.filter(column=col))
            if not links:
                continue
            group = NavigationLinkGroup.objects.create(
                name=f"{col.heading or 'Navigation'} (column {col.pk})"
            )
            for link in links:
                NavigationLink.objects.create(
                    group=group,
                    sort_order=link.sort_order or 0,
                    label=link.label,
                    url=link.url,
                )
            col.nav_group = group
            col.save(update_fields=["nav_group"])

        elif col.column_type == "social":
            links = list(FooterColumnLink.objects.filter(column=col))
            if not links:
                continue
            group = SocialMediaGroup.objects.create(
                name=f"Social (column {col.pk})"
            )
            for link in links:
                SocialLink.objects.create(
                    group=group,
                    sort_order=link.sort_order or 0,
                    label=link.label,
                    url=link.url,
                    icon_class=link.icon_class,
                )
            col.social_group = group
            col.save(update_fields=["social_group"])


def reverse_migrate(apps, schema_editor):
    FooterColumn = apps.get_model("home", "FooterColumn")
    NavigationLinkGroup = apps.get_model("home", "NavigationLinkGroup")
    SocialMediaGroup = apps.get_model("home", "SocialMediaGroup")
    FooterColumn.objects.all().update(nav_group=None, social_group=None)
    NavigationLinkGroup.objects.all().delete()
    SocialMediaGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_remove_footercolumn2link_settings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationLinkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Navigation link group",
                "verbose_name_plural": "Navigation link groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Social media group",
                "verbose_name_plural": "Social media groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent link for nesting. Blank = top-level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="home.navigationlink",
                    ),
                ),
                (
                    "group",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="home.navigationlinkgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="footercolumn",
            name="nav_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.navigationlinkgroup",
                verbose_name="Navigation links",
            ),
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-twitter-x).",
                        max_length=40,
                    ),
                ),
                (
                    "group",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="home.socialmediagroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="footercolumn",
            name="social_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.socialmediagroup",
                verbose_name="Social links",
            ),
        ),
        # Data migration: migrate existing FooterColumnLink data into snippet groups
        migrations.RunPython(migrate_column_links, reverse_migrate),
        # Then remove the old model
        migrations.DeleteModel(name="FooterColumnLink"),
    ]
