# Generated by Django 6.0.6 on 2026-06-15 11:15

import json

import wagtail.fields
from django.db import migrations


def migrate_column_data(apps, schema_editor):
    FooterColumn = apps.get_model("home", "FooterColumn")
    for col in FooterColumn.objects.all():
        block_data = None
        if col.column_type == "navigation" and col.nav_group_id:
            block_data = {"type": "navigation", "value": {"nav_group": col.nav_group_id}}
        elif col.column_type == "social" and col.social_group_id:
            block_data = {
                "type": "social",
                "value": {
                    "social_group": col.social_group_id,
                    "icon_size": col.icon_size or "medium",
                    "icon_position": col.icon_position or "left",
                },
            }
        elif col.column_type == "newsletter":
            block_data = {
                "type": "newsletter",
                "value": {
                    "description": col.newsletter_description or "",
                    "placeholder_text": col.placeholder_text or "Your email",
                    "button_label": col.button_label or "Subscribe",
                    "button_url": col.button_url or "",
                },
            }
        elif col.column_type == "text":
            block_data = {
                "type": "text",
                "value": {"body": col.body or ""},
            }
        elif col.column_type == "image" and col.image_id:
            block_data = {
                "type": "image",
                "value": {
                    "image": col.image_id,
                    "image_height": col.image_height,
                    "image_position": col.image_position or "left",
                },
            }

        if block_data:
            col.content = json.dumps([block_data])
            col.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_navigationlinkgroup_socialmediagroup_navigationlink_and_more"),
    ]

    operations = [
        # Step 1: Add the StreamField
        migrations.AddField(
            model_name="footercolumn",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("navigation", 1),
                    ("social", 5),
                    ("newsletter", 10),
                    ("text", 12),
                    ("image", 16),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.NavigationLinkGroup",),
                        {},
                    ),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("nav_group", 0)]],
                        {},
                    ),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.SocialMediaGroup",),
                        {},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("social_group", 2),
                                ("icon_size", 3),
                                ("icon_position", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Your email", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Subscribe", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Form action URL.", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("description", 6),
                                ("placeholder_text", 7),
                                ("button_label", 8),
                                ("button_url", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.RichTextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 11)]],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    14: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Leave blank for natural height.",
                            "label": "Max height (px)",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "label": "Alignment",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 13),
                                ("image_height", 14),
                                ("image_position", 15),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        # Step 2: Data migration
        migrations.RunPython(migrate_column_data, migrations.RunPython.noop),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name="footercolumn",
            name="body",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="button_label",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="button_url",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="column_type",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="icon_position",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="icon_size",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="image",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="image_position",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="nav_group",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="newsletter_description",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="placeholder_text",
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="social_group",
        ),
    ]
