# Generated by Django 6.0.6 on 2026-06-15 11:37

import json

import wagtail.fields
from django.db import migrations


def migrate_columns(apps, schema_editor):
    FooterSettings = apps.get_model("home", "FooterSettings")
    FooterColumn = apps.get_model("home", "FooterColumn")

    # Group columns by settings pk, ordered by sort_order
    columns_by_settings = {}
    for col in FooterColumn.objects.all().order_by("sort_order"):
        columns_by_settings.setdefault(col.settings_id, []).append(col)

    for settings_pk, columns in columns_by_settings.items():
        try:
            fs = FooterSettings.objects.get(pk=settings_pk)
        except FooterSettings.DoesNotExist:
            continue

        blocks = []
        for col in columns:
            raw = col.content.raw_text if col.content else None
            inner = json.loads(raw) if raw else []
            if inner:
                block = inner[0]
                # Inject width and heading from the column into the block value
                block["value"]["width"] = col.width
                block["value"]["heading"] = col.heading
                blocks.append(block)

        if blocks:
            fs.columns = json.dumps(blocks)
            fs.save(update_fields=["columns"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_remove_footercolumn_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="columns",
            field=wagtail.fields.StreamField(
                [
                    ("navigation", 3),
                    ("social", 7),
                    ("newsletter", 12),
                    ("text", 14),
                    ("image", 18),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (25, "25%"),
                                (33, "33%"),
                                (50, "50%"),
                                (66, "66%"),
                                (75, "75%"),
                                (100, "100%"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 80, "required": False},
                    ),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.NavigationLinkGroup",),
                        {},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("heading", 1), ("nav_group", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.SocialMediaGroup",),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("heading", 1),
                                ("social_group", 4),
                                ("icon_size", 5),
                                ("icon_position", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Your email", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Subscribe", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Form action URL.", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("heading", 1),
                                ("description", 8),
                                ("placeholder_text", 9),
                                ("button_label", 10),
                                ("button_url", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.RichTextBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 0), ("heading", 1), ("body", 13)]],
                        {},
                    ),
                    15: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Leave blank for natural height.",
                            "label": "Max height (px)",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "label": "Alignment",
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 0),
                                ("heading", 1),
                                ("image", 15),
                                ("image_height", 16),
                                ("image_position", 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.RunPython(migrate_columns, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="FooterColumn",
        ),
    ]
