# Generated by Django 6.0.6 on 2026-06-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_navbarsettings_nav_group_delete_navbarlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarsettings',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='logo_text',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='nav_group',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='sticky',
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='layout',
            field=models.CharField(choices=[('logo_left_center', 'Logo left, nav center'), ('logo_centered', 'Logo centered, nav below'), ('logo_left_split', 'Logo left, CTA right, nav center'), ('logo_left_center_below', 'Logo left, nav center below'), ('logo_minimal', 'Minimal (hamburger default)')], default='logo_left_center', max_length=40, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.navigationlinkgroup', verbose_name='Navigation links'),
        ),
    ]
