# Generated by Django 6.0.6 on 2026-06-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_navbarsettings_cta_label_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='CTA button label'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='cta_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='CTA button URL'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='logo_text',
            field=models.CharField(blank=True, default='Site name', help_text='Shown as text logo when no image is set.', max_length=120, verbose_name='Logo text'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='nav_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.navigationlinkgroup', verbose_name='Navigation links'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='sticky',
            field=models.BooleanField(default=False, help_text='Keep the navbar fixed at the top when scrolling.', verbose_name='Sticky navbar'),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Upload a logo image. If empty, logo_text is shown as text logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo image'),
        ),
    ]
