# Generated by Django 6.0.6 on 2026-06-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_navbarsettings_anchor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='section_height',
            field=models.PositiveIntegerField(default=60, help_text='Height of the navbar in pixels.', verbose_name='Section height (px)'),
        ),
    ]
