# Generated by Django 6.0.6 on 2026-06-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_navbar_section_height_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='nav_scroll_animation',
            field=models.CharField(choices=[('none', 'None'), ('shrink', 'Shrink'), ('reveal', 'Reveal on scroll up')], default='none', help_text='Animate the navbar when scrolling.', max_length=20, verbose_name='Scroll animation'),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='nav_transparent',
            field=models.BooleanField(default=False, help_text='When enabled, the navbar starts transparent and gains its background color when scrolled.', verbose_name='Transparent navbar'),
        ),
    ]
