# Generated by Django 6.0.6 on 2026-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_social_link_platform_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('threads', 'Threads'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('line', 'LINE'), ('tumblr', 'Tumblr'), ('medium', 'Medium'), ('github', 'GitHub')], default='github', max_length=20, verbose_name='Platform'),
        ),
    ]
