# Generated by Django 6.0.6 on 2026-06-16 17:41

import django.db.models.deletion
from django.db import migrations, models


def use_marked_default_theme(apps, schema_editor):
    ColorTheme = apps.get_model("home", "ColorTheme")
    DesignSystemSettings = apps.get_model("home", "DesignSystemSettings")
    default_theme = ColorTheme.objects.filter(is_default=True).first()
    if default_theme:
        DesignSystemSettings.objects.filter(global_theme__isnull=True).update(
            global_theme=default_theme
        )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_quora_substack_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsystemsettings',
            name='global_theme',
            field=models.ForeignKey(blank=True, help_text='Select a color theme for the entire site. Color pickers are available in Snippets → Color themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='clients_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Clients color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='CTA color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Features color theme'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colortheme', verbose_name='Hero color theme'),
        ),
        migrations.RunPython(use_marked_default_theme, migrations.RunPython.noop),
    ]
