# Generated by Django 6.0.6 on 2026-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_replace_themes_with_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortheme',
            name='body_text_color',
            field=models.CharField(blank=True, default='', help_text='Paragraphs, copy, and general body content.', max_length=32, verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='brand_glow',
            field=models.CharField(blank=True, default='', help_text='Hero centered radial gradient spot.', max_length=32, verbose_name='Brand glow'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='button_primary_bg',
            field=models.CharField(blank=True, default='', help_text='Main call-to-action button background.', max_length=32, verbose_name='Primary button'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='button_primary_hover',
            field=models.CharField(blank=True, default='', help_text='Primary button on hover.', max_length=32, verbose_name='Primary button hover'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='button_secondary_border',
            field=models.CharField(blank=True, default='', help_text='Secondary outline button border and text.', max_length=32, verbose_name='Secondary button'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='button_secondary_hover_bg',
            field=models.CharField(blank=True, default='', help_text='Secondary button fill on hover.', max_length=32, verbose_name='Secondary button hover bg'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='check_color',
            field=models.CharField(blank=True, default='', help_text='Checklist checkmarks.', max_length=32, verbose_name='Checklist color'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='feature_icon_bg',
            field=models.CharField(blank=True, default='', help_text='Feature section icon backgrounds.', max_length=32, verbose_name='Feature icon bg'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='feature_icon_text',
            field=models.CharField(blank=True, default='', help_text='Text inside feature icons.', max_length=32, verbose_name='Feature icon text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='footer_bg',
            field=models.CharField(blank=True, default='', help_text='Footer background.', max_length=32, verbose_name='Footer background'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='footer_heading_color',
            field=models.CharField(blank=True, default='', help_text='Footer column headings.', max_length=32, verbose_name='Footer heading'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='footer_link_color',
            field=models.CharField(blank=True, default='', help_text='Footer links.', max_length=32, verbose_name='Footer link'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='footer_link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Footer links on hover.', max_length=32, verbose_name='Footer link hover'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='footer_text_color',
            field=models.CharField(blank=True, default='', help_text='Footer body text.', max_length=32, verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='heading_text_color',
            field=models.CharField(blank=True, default='', help_text='H1–H6 and display headings.', max_length=32, verbose_name='Heading text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='link_color',
            field=models.CharField(blank=True, default='', help_text='Text links, announcement links, eyebrow links.', max_length=32, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Link text on hover.', max_length=32, verbose_name='Link hover'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='muted_text_color',
            field=models.CharField(blank=True, default='', help_text='Secondary paragraphs, lead text, announcements.', max_length=32, verbose_name='Muted text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='navbar_bg',
            field=models.CharField(blank=True, default='', help_text='Navbar bar background.', max_length=32, verbose_name='Navbar background'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='navbar_link_color',
            field=models.CharField(blank=True, default='', help_text='Navbar navigation links.', max_length=32, verbose_name='Navbar link'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='navbar_link_hover_color',
            field=models.CharField(blank=True, default='', help_text='Navbar links on hover.', max_length=32, verbose_name='Navbar link hover'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='navbar_text_color',
            field=models.CharField(blank=True, default='', help_text='Navbar text and brand.', max_length=32, verbose_name='Navbar text'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='page_bg',
            field=models.CharField(blank=True, default='', help_text='Body and section background.', max_length=32, verbose_name='Page background'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='surface_bg',
            field=models.CharField(blank=True, default='', help_text='Media placeholders, card fills.', max_length=32, verbose_name='Surface background'),
        ),
        migrations.AlterField(
            model_name='colortheme',
            name='surface_border',
            field=models.CharField(blank=True, default='', help_text='Card borders, grid lines, dividers, media frames.', max_length=32, verbose_name='Surface border'),
        ),
    ]
