# Generated by Django 6.0.6 on 2026-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_blogindexpage_header_overlay_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_overlay_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Color tint for the background image overlay.', max_length=32, verbose_name='Overlay color'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='header_overlay_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=32, verbose_name='Overlay color'),
        ),
    ]
