# Generated by Django 6.0.6 on 2026-06-17 17:58

import wagtail.fields
from django.db import migrations


def image_url(label):
    return f"https://dummyimage.com/220x80/101624/ffffff.png&text={label.replace(' ', '+')}"


def migrate_client_names_to_logos(apps, schema_editor):
    KoderstoryHomePage = apps.get_model("home", "KoderstoryHomePage")
    for page in KoderstoryHomePage.objects.all():
        migrated = []
        for index, block in enumerate(page.clients or [], start=1):
            value = block.value
            name = value.get("name") or f"Company {index}"
            migrated.append((
                "client",
                {
                    "fallback_image_url": image_url(name),
                    "image_alt": f"{name} logo",
                    "url": value.get("url", ""),
                },
            ))
        if not migrated:
            migrated = [
                ("client", {"fallback_image_url": image_url(f"Company {index}"), "image_alt": f"Company {index} logo"})
                for index in range(1, 6)
            ]
        page.clients = migrated
        page.save()


def reverse_client_logos_to_names(apps, schema_editor):
    KoderstoryHomePage = apps.get_model("home", "KoderstoryHomePage")
    for page in KoderstoryHomePage.objects.all():
        page.clients = [
            ("client", {"name": f"Company {index}"})
            for index, _block in enumerate(page.clients or [], start=1)
        ]
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_koderstoryhomepage_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koderstoryhomepage',
            name='clients',
            field=wagtail.fields.StreamField([('client', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used when no Wagtail image is selected.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('fallback_image_url', 1), ('image_alt', 2), ('url', 3)]], {})}),
        ),
        migrations.RunPython(migrate_client_names_to_logos, reverse_client_logos_to_names),
    ]
