# Generated by Django 5.1.15 on 2026-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0002_repair_sqlite_primary_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typographysettings',
            options={},
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h1_font',
            field=models.CharField(blank=True, help_text="Font family for H1 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h2_font',
            field=models.CharField(blank=True, help_text="Font family for H2 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h3_font',
            field=models.CharField(blank=True, help_text="Font family for H3 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h4_font',
            field=models.CharField(blank=True, help_text="Font family for H4 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h5_font',
            field=models.CharField(blank=True, help_text="Font family for H5 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='h6_font',
            field=models.CharField(blank=True, help_text="Font family for H6 headings (e.g., 'Inter', 'Playfair Display')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='paragraph_font',
            field=models.CharField(blank=True, help_text="Font family for paragraph text (e.g., 'Inter', 'Open Sans')", max_length=255),
        ),
        migrations.AlterField(
            model_name='typographysettings',
            name='paragraph_font_weight',
            field=models.CharField(blank=True, help_text="Font weight for paragraph text (e.g., 'normal', '300', '400', '500', '600')", max_length=50),
        ),
    ]
