# Generated by Django 6.0.6 on 2026-06-12 06:58

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('centered', 'Centered'), ('image_right', 'Image right'), ('dark', 'Dark')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('variant', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 4), ('secondary_button_url', 5), ('image', 6), ('image_alt', 7)]], {})})),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('centered', 'Centered'), ('image_right', 'Image right'), ('dark', 'Dark')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('variant', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 4), ('secondary_button_url', 5), ('image', 6), ('image_alt', 7)]], {})})),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('body', wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('centered', 'Centered'), ('image_right', 'Image right'), ('dark', 'Dark')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('variant', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 4), ('secondary_button_url', 5), ('image', 6), ('image_alt', 7)]], {})})),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('centered', 'Centered'), ('image_right', 'Image right'), ('dark', 'Dark')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('variant', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 4), ('secondary_button_url', 5), ('image', 6), ('image_alt', 7)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('centered', 'Centered'), ('image_right', 'Image right'), ('dark', 'Dark')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('variant', 0), ('eyebrow', 1), ('heading', 2), ('body', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 4), ('secondary_button_url', 5), ('image', 6), ('image_alt', 7)]], {})})),
                ('date', models.DateField(verbose_name='Post date')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='pages.formpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
