def default_color_schemes():
    return {
        "white": {
            "background": "#ffffff",
            "border": "#e5e7eb",
            "heading": "#111827",
            "text": "#4b5563",
            "link": "#4338ca",
            "primary_button_background": "#4f46e5",
            "primary_button_text": "#ffffff",
            "primary_button_border": "#4f46e5",
            "secondary_button_background": "#ffffff",
            "secondary_button_text": "#111827",
            "secondary_button_border": "#d1d5db",
        },
        "light": {
            "background": "#f8fafc",
            "border": "#e2e8f0",
            "heading": "#0f172a",
            "text": "#475569",
            "link": "#4f46e5",
            "primary_button_background": "#4f46e5",
            "primary_button_text": "#ffffff",
            "primary_button_border": "#4f46e5",
            "secondary_button_background": "#ffffff",
            "secondary_button_text": "#0f172a",
            "secondary_button_border": "#cbd5e1",
        },
        "dark": {
            "background": "#111827",
            "border": "#374151",
            "heading": "#f9fafb",
            "text": "#d1d5db",
            "link": "#a5b4fc",
            "primary_button_background": "#e0e7ff",
            "primary_button_text": "#111827",
            "primary_button_border": "#e0e7ff",
            "secondary_button_background": "transparent",
            "secondary_button_text": "#f9fafb",
            "secondary_button_border": "#4b5563",
        },
        "black": {
            "background": "#000000",
            "border": "#262626",
            "heading": "#ffffff",
            "text": "#d4d4d4",
            "link": "#e0e7ff",
            "primary_button_background": "#ffffff",
            "primary_button_text": "#000000",
            "primary_button_border": "#ffffff",
            "secondary_button_background": "transparent",
            "secondary_button_text": "#ffffff",
            "secondary_button_border": "#404040",
        },
        "highlight": {
            "background": "#ecfe3a",
            "border": "#d9f99d",
            "heading": "#111827",
            "text": "#374151",
            "link": "#111827",
            "primary_button_background": "#111827",
            "primary_button_text": "#ffffff",
            "primary_button_border": "#111827",
            "secondary_button_background": "transparent",
            "secondary_button_text": "#111827",
            "secondary_button_border": "#111827",
        },
        "brand": {
            "background": "#eef2ff",
            "border": "#c7d2fe",
            "heading": "#111827",
            "text": "#4b5563",
            "link": "#4338ca",
            "primary_button_background": "#4f46e5",
            "primary_button_text": "#ffffff",
            "primary_button_border": "#4f46e5",
            "secondary_button_background": "#ffffff",
            "secondary_button_text": "#111827",
            "secondary_button_border": "#c7d2fe",
        },
    }


SECTION_SPACING_TOKENS = {
    "compact": "3rem",
    "normal": "5rem",
    "spacious": "7rem",
}

CONTAINER_WIDTH_TOKENS = {
    "narrow": "48rem",
    "normal": "72rem",
    "wide": "88rem",
    "full": "100%",
}
