# Generated by Django 6.0.6 on 2026-06-12 10:40

import wagtail.fields
from django.db import migrations


def populate_homepage_body(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")

    homepage = HomePage.objects.filter(slug="home").first()
    if homepage is None:
        return

    homepage.body = [
        (
            "hero",
            {
                "anchor_id": "hero",
                "eyebrow": "Custom digital systems",
                "title": "Practical digital systems for business operations and growth",
                "description": (
                    "Koderstory builds custom web applications, ERP workflows, "
                    "dashboards, mobile tools, and automation systems that help "
                    "businesses organize operations and grow with clearer systems."
                ),
                "buttons": [
                    {
                        "label": "Start project",
                        "url": "#contact",
                        "style": "primary",
                    },
                    {
                        "label": "View work",
                        "url": "#services",
                        "style": "secondary",
                    },
                ],
            },
        ),
        (
            "client_logos",
            {
                "anchor_id": "clients",
                "title": "Experience across digital products and operations",
                "items": ["Client 01", "Client 02", "Client 03", "Client 04"],
            },
        ),
        (
            "card_grid",
            {
                "anchor_id": "services",
                "kicker": "Services",
                "title": "Build the right system for the right business need",
                "title_class": "h3",
                "description": "Start from your current workflow, problem, or operational bottleneck.",
                "section_link": {
                    "label": "View all services",
                    "url": "#contact",
                    "style": "secondary",
                },
                "columns": "3",
                "cards": [
                    {
                        "eyebrow": "Web app",
                        "title": "Custom Web Application",
                        "description": "Business systems, portals, internal tools, and operational workflows.",
                        "button": {
                            "label": "View service",
                            "url": "#contact",
                            "style": "secondary",
                        },
                    },
                    {
                        "eyebrow": "ERP",
                        "title": "Odoo / ERP",
                        "description": "ERP implementation, workflow customization, and operations improvement.",
                        "button": {
                            "label": "View service",
                            "url": "#contact",
                            "style": "secondary",
                        },
                    },
                    {
                        "eyebrow": "Dashboard",
                        "title": "Business Dashboard",
                        "description": "Reporting and KPI visibility for operations, finance, and decision making.",
                        "button": {
                            "label": "View service",
                            "url": "#contact",
                            "style": "secondary",
                        },
                    },
                ],
            },
        ),
        (
            "card_grid",
            {
                "anchor_id": "products",
                "kicker": "Products",
                "title": "Products and solution concepts",
                "title_class": "display-5",
                "description": "",
                "section_link": {
                    "label": "View all products",
                    "url": "#contact",
                    "style": "secondary",
                },
                "columns": "2",
                "cards": [
                    {
                        "eyebrow": "Hospitality",
                        "title": "SIRASA",
                        "description": "Hotel and partner merchant QR ordering system concept.",
                        "button": {
                            "label": "View product",
                            "url": "#contact",
                            "style": "secondary",
                        },
                    },
                    {
                        "eyebrow": "Education",
                        "title": "BIMORA",
                        "description": "Management system concept for tutoring and education administration.",
                        "button": {
                            "label": "View product",
                            "url": "#contact",
                            "style": "secondary",
                        },
                    },
                ],
            },
        ),
        (
            "cta",
            {
                "anchor_id": "cta",
                "kicker": "Start a project",
                "title": "Need a practical system for your business?",
                "description": "Start with your process, problem, or product idea.",
                "buttons": [
                    {
                        "label": "Fill project form",
                        "url": "#contact",
                        "style": "primary",
                    },
                    {
                        "label": "Contact",
                        "url": "mailto:aldy@koderstory.com",
                        "style": "secondary",
                    },
                ],
            },
        ),
    ]
    homepage.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 12), ('client_logos', 15), ('card_grid', 24), ('cta', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'hero', 'help_text': 'Used for the top navigation anchor.', 'max_length': 32, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 3: ('wagtail.blocks.TextBlock', (), {'rows': 4}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')], 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('page', 5), ('url', 6), ('style', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'max_num': 2, 'min_num': 1}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('eyebrow', 1), ('title', 2), ('description', 3), ('buttons', 9), ('image', 10), ('image_alt', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'clients', 'help_text': 'Used for the top navigation anchor.', 'max_length': 32, 'required': False}), 14: ('wagtail.blocks.ListBlock', (4,), {'max_num': 8, 'min_num': 4}), 15: ('wagtail.blocks.StructBlock', [[('anchor_id', 13), ('eyebrow', 1), ('title', 2), ('items', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'services', 'help_text': 'Used for the top navigation anchor.', 'max_length': 32, 'required': False}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h3', 'Heading'), ('display-5', 'Display')], 'required': False}), 18: ('wagtail.blocks.TextBlock', (), {'required': False, 'rows': 3}), 19: ('wagtail.blocks.StructBlock', [[('label', 4), ('page', 5), ('url', 6), ('style', 7)]], {'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns')], 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 1), ('title', 21), ('description', 3), ('image', 10), ('image_alt', 11), ('button', 19)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'min_num': 1}), 24: ('wagtail.blocks.StructBlock', [[('anchor_id', 16), ('kicker', 4), ('title', 2), ('title_class', 17), ('description', 18), ('section_link', 19), ('columns', 20), ('cards', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'contact', 'help_text': 'Used for the top navigation anchor.', 'max_length': 32, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('anchor_id', 25), ('kicker', 1), ('title', 2), ('description', 18), ('buttons', 9)]], {})}, help_text='Build the homepage from reusable Bootstrap-inspired sections.', verbose_name='Page sections'),
        ),
        migrations.RunPython(populate_homepage_body, migrations.RunPython.noop),
    ]
