# Generated by Django 6.0.6 on 2026-06-12 11:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


HOMEPAGE_DEFAULTS = {
    "hero_anchor_id": "hero",
    "hero_eyebrow": "Custom digital systems",
    "hero_title": "Practical digital systems for business operations and growth",
    "hero_description": (
        "Koderstory builds custom web applications, ERP workflows, dashboards, "
        "mobile tools, and automation systems that help businesses organize "
        "operations and grow with clearer systems."
    ),
    "hero_primary_button_label": "Start project",
    "hero_primary_button_url": "#contact",
    "hero_secondary_button_label": "View work",
    "hero_secondary_button_url": "#services",
    "clients_anchor_id": "clients",
    "clients_title": "Experience across digital products and operations",
    "services_anchor_id": "services",
    "services_kicker": "Services",
    "services_title": "Build the right system for the right business need",
    "services_description": "Start from your current workflow, problem, or operational bottleneck.",
    "services_button_label": "View all services",
    "services_button_url": "#contact",
    "products_anchor_id": "products",
    "products_kicker": "Products",
    "products_title": "Products and solution concepts",
    "products_button_label": "View all products",
    "products_button_url": "#contact",
    "cta_anchor_id": "cta",
    "cta_kicker": "Start a project",
    "cta_title": "Need a practical system for your business?",
    "cta_description": "Start with your process, problem, or product idea.",
    "cta_primary_button_label": "Fill project form",
    "cta_primary_button_url": "#contact",
    "cta_secondary_button_label": "Contact",
    "cta_secondary_button_url": "mailto:aldy@koderstory.com",
}


def populate_homepage_sections(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    HomeClientLogo = apps.get_model("home", "HomeClientLogo")
    HomeServiceCard = apps.get_model("home", "HomeServiceCard")
    HomeProductCard = apps.get_model("home", "HomeProductCard")

    for homepage in HomePage.objects.all():
        for field_name, value in HOMEPAGE_DEFAULTS.items():
            if not getattr(homepage, field_name):
                setattr(homepage, field_name, value)
        homepage.save(update_fields=list(HOMEPAGE_DEFAULTS.keys()))

        if not HomeClientLogo.objects.filter(page=homepage).exists():
            for sort_order, name in enumerate(["Client 01", "Client 02", "Client 03", "Client 04"]):
                HomeClientLogo.objects.create(
                    page=homepage,
                    name=name,
                    sort_order=sort_order,
                )

        if not HomeServiceCard.objects.filter(page=homepage).exists():
            service_cards = [
                (
                    "Web app",
                    "Custom Web Application",
                    "Business systems, portals, internal tools, and operational workflows.",
                ),
                (
                    "ERP",
                    "Odoo / ERP",
                    "ERP implementation, workflow customization, and operations improvement.",
                ),
                (
                    "Dashboard",
                    "Business Dashboard",
                    "Reporting and KPI visibility for operations, finance, and decision making.",
                ),
            ]
            for sort_order, (eyebrow, title, description) in enumerate(service_cards):
                HomeServiceCard.objects.create(
                    page=homepage,
                    eyebrow=eyebrow,
                    title=title,
                    description=description,
                    button_label="View service",
                    button_url="#contact",
                    sort_order=sort_order,
                )

        if not HomeProductCard.objects.filter(page=homepage).exists():
            product_cards = [
                (
                    "Hospitality",
                    "SIRASA",
                    "Hotel and partner merchant QR ordering system concept.",
                ),
                (
                    "Education",
                    "BIMORA",
                    "Management system concept for tutoring and education administration.",
                ),
            ]
            for sort_order, (eyebrow, title, description) in enumerate(product_cards):
                HomeProductCard.objects.create(
                    page=homepage,
                    eyebrow=eyebrow,
                    title=title,
                    description=description,
                    button_label="View product",
                    button_url="#contact",
                    sort_order=sort_order,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients_anchor_id',
            field=models.CharField(blank=True, default='clients', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_anchor_id',
            field=models.CharField(blank=True, default='cta', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_kicker',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_anchor_id',
            field=models.CharField(blank=True, default='hero', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_anchor_id',
            field=models.CharField(blank=True, default='products', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_kicker',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_anchor_id',
            field=models.CharField(blank=True, default='services', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_kicker',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='HomeClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_logos', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_alt', models.CharField(blank=True, max_length=120)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_alt', models.CharField(blank=True, max_length=120)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RunPython(populate_homepage_sections, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
