# Generated by Django 6.0.6 on 2026-06-12 11:59

from django.db import migrations, models


def enable_existing_homepage_buttons(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    HomePage.objects.update(hero_buttons_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_clients_anchor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_buttons_enabled',
            field=models.BooleanField(default=False, help_text='Show or hide the hero call-to-action buttons.', verbose_name='Enable hero buttons'),
        ),
        migrations.RunPython(enable_existing_homepage_buttons, migrations.RunPython.noop),
    ]
