# Generated by Django 6.0.6 on 2026-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_buttons_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_layout',
            field=models.CharField(choices=[('centered_simple', 'Centered simple'), ('centered_preview', 'Centered with preview image'), ('split_image_right', 'Split image right'), ('angled_image_right', 'Angled image right')], default='split_image_right', help_text='Choose how the hero content and image are arranged.', max_length=40),
        ),
    ]
