# Generated by Django 6.0.6 on 2026-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_hero_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade_in', 'Fade in'), ('slide_up', 'Slide up')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('large', 'Large'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_heading_category',
            field=models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3')], default='heading_2', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_text_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade_in', 'Fade in'), ('slide_up', 'Slide up')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('large', 'Large'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_heading_category',
            field=models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3')], default='heading_2', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade_in', 'Fade in'), ('slide_up', 'Slide up')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('large', 'Large'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading_category',
            field=models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3')], default='heading_1', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade_in', 'Fade in'), ('slide_up', 'Slide up')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('large', 'Large'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_heading_category',
            field=models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3')], default='heading_2', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_text_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade_in', 'Fade in'), ('slide_up', 'Slide up')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_button_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_content_horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_content_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('large', 'Large'), ('full', 'Full width')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading_category',
            field=models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3')], default='heading_2', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_height',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_text_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=16),
        ),
    ]
