# Generated by Django 6.0.6 on 2026-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_clients_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the client logo section without deleting its content.', verbose_name='Enable client logo section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the CTA section without deleting its content.', verbose_name='Enable CTA section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the hero section without deleting its content.', verbose_name='Enable hero section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the products section without deleting its content.', verbose_name='Enable products section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the services section without deleting its content.', verbose_name='Enable services section'),
        ),
    ]
