# Generated by Django 6.0.6 on 2026-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_clients_enabled_homepage_cta_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients_layout',
            field=models.CharField(choices=[('card_split', 'Card split'), ('heading_top', 'Heading top'), ('cta_bottom', 'CTA bottom'), ('split_grid', 'Split grid'), ('simple_row', 'Simple row'), ('dark_grid', 'Dark grid'), ('dark_row', 'Dark row')], default='card_split', help_text='Choose the visual layout for client logos.', max_length=32),
        ),
    ]
