# Generated by Django 6.0.6 on 2026-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_clients_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_layout',
            field=models.CharField(choices=[('card_grid', 'Card grid'), ('media_right', 'Media right'), ('centered_grid', 'Centered grid'), ('dark_media', 'Dark media'), ('media_top', 'Media top'), ('media_left', 'Media left'), ('simple_columns', 'Simple columns'), ('checklist', 'Checklist'), ('dark_grid', 'Dark grid')], default='card_grid', help_text='Choose the visual layout for service cards.', max_length=32),
        ),
    ]
