# Generated by Django 6.0.6 on 2026-06-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_services_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_layout',
            field=models.CharField(choices=[('split', 'Split'), ('left_stack', 'Left stack'), ('centered', 'Centered'), ('dark_centered', 'Dark centered'), ('gradient_centered', 'Gradient centered'), ('bar', 'Bar'), ('split_media', 'Split media'), ('media_left', 'Media left'), ('benefit_grid', 'Benefit grid')], default='split', help_text='Choose the visual layout for the CTA section.', max_length=32),
        ),
    ]
